### ISSUE TITLE
magit-log--add-date-headers causes an error

### ISSUE THREAD

**Issue by ReneFroger** [alphapapa/unpackaged.el#1]
Thanks for sharing it, it's appreciated. I have earlier asked on Reddit, but this seems be a better place to keep it tidy.

### Version and how to reproduce
I use Emacs build 27.0.50, GTK+version. 
Then use following code [long code!].
```
            (use-package magit
            :ensure t)

            (use-package ov
            :ensure t)

            (defun unpackaged/magit-log--add-date-headers (&rest _ignore)
            "Add date headers to Magit log buffers."
            (when (derived-mode-p 'magit-log-mode)
                (save-excursion
                (goto-char (point-min))
                (ov-clear 'date-header t)
                (--> (cl-loop for ov in (cdr (ov-all))
                                for margin-text = (-some--> (ov-val ov 'before-string)
                                                            (cadr (get-text-property 0 'display it)))
                                when margin-text
                                for age = (when (string-match (rx (group (1+ digit) ; number
                                                                        " "
                                                                        (1+ (not blank))) ; unit
                                                                (1+ blank) eol)
                                                            margin-text)
                                            (match-string-no-properties 1 margin-text))
                                collect (cons age (ov-beg ov)))
                    (-group-by #'car it)
                    (--map (cons (car it) (-sort (-on #'< #'cdr) (cdr it)))
                            it)
                    (--map (cons (car it) (cdadr it)) it)
                    (cl-loop for (age . pos) in it
                                do (ov (1- pos) (1- pos)
                                    'after-string (propertize (concat " " age "\n")
                                                                'face 'magit-section-heading)
                                    'date-header t))))))

(add-hook 'magit-post-refresh-hook #'unpackaged/magit-log--add-date-headers)
(advice-add #'magit-mode-setup :after #'unpackaged/magit-log--add-date-headers)

```
Then I load Magit's log, go to any file in any Git repository with `M-x magit-log-all`, then I got the following error in minibuffer:

> -sort: Symbol’s function definition is void: -on

which might be caused in this line in the function

`(--map (cons (car it) (-sort (-on #'< #'cdr) (cdr it)))
`

@alphapapa , when trying to solve it, I looked around ,but I found no Elisp reference for `on` so far. Perhaps you could tell me what's happening here, as you might be able to reproduce this?

**Comment by ReneFroger** [comment]
Seems this was already solved on Reddit. It's caused by missing `dash.el`.

**Comment by alphapapa** [comment]
Yes, sorry, I forgot that `-on` is part of `dash-functional`, which is not automatically loaded by `(require 'dash)`.  I added mention of this just now: https://github.com/alphapapa/unpackaged.el/commit/8a05a173f42f0cf34acae5f5327477f26548acf2

I suppose this is part of the "hazard" of publishing these "unpackaged".  :)  Maybe I should add `(eval-and-compile (require 'dash-functional))` to that function definition...
