### ISSUE TITLE
Small fix for refile to datetree file using timestamp in entry

### ISSUE THREAD

**Issue by brabalan** [alphapapa/unpackaged.el#10]
The function `unpackaged/org-timestamps-in-entry` in https://github.com/alphapapa/unpackaged.el#refile-to-datetree-file-using-earliestlatest-timestamp-in-entry should use `collect (ts-parse-org-element ts)` instead of `collect (ts-parse-org ts)`.

**Comment by alphapapa** [comment]
Hi Alan,

Thank you very much, I don't know how I made that mistake.  I fixed it by calling `ts-parse-org` with the match string, which should be faster than using the element-based one.
