### ISSUE TITLE
Option to replace contents in `unpackaged/lorem-ipsum-overlay'

### ISSUE THREAD

**Issue by mtekman** [alphapapa/unpackaged.el#14]
Hey, so I experienced massive slowdowns when applying this to my org-mode file of ~10,000 lines and ~90,000 words.

As a workaround I changed two lines, so that it would not use overlays and instead perform an actual replacement.

I've attached is a patch file below :+1: 

[diff.patch.txt](https://github.com/alphapapa/unpackaged.el/files/4441262/diff.patch.txt)

**Comment by alphapapa** [comment]
Thanks.  You might want to use `(setf (buffer-substring beg end) ...)` rather than `replace-rectangle`, which is probably not the right thing to use.

I'll probably add this as an option using a prefix argument to replace rather than overlay the contents.

**Comment by mtekman** [comment]
I'm still not 100% sure on the usage of setf (it sets the cdr?), but good to know.

And yep, was also disappointed by that

**Comment by alphapapa** [comment]
Sorry for the delay.  Would you please test this branch and let me know how it works for you?

**Comment by mtekman** [comment]
tested, and working -- thanks!
