### ISSUE TITLE
Pre blocks on mobile view extend beyond the box boundaries

### ISSUE THREAD

**Issue by seshaljain** [alphapapa/unpackaged.el#15]
https://github.com/alphapapa/unpackaged.el/blob/5476a7d266fd02cdaab2ba73132956a57515171e/index.html#L43

I believe change L43 to `overflow-x: auto` should solve this problem. But is this being generated by an exporter?

**Comment by alphapapa** [comment]
Yes, it's generated by `ox-html`.  We could override the CSS, but I don't think it would be worth the trouble.  That HTML isn't really intended for mobile browsers.

**Comment by seshaljain** [comment]
Okay 😄
