### ISSUE TITLE
An alternative to feed-for-url

### ISSUE THREAD

**Issue by yantar92** [alphapapa/unpackaged.el#19]
There is https://github.com/HKey/feed-discovery package doing the same job (AFAIU).

**Comment by alphapapa** [comment]
Thanks.  Glancing at its code, I'm not sure which is really better to recommend.

**Comment by yantar92** [comment]
> Thanks.  Glancing at its code, I'm not sure which is really better to recommend.

I guess a proper package would be a better choice to use as a dependency
in another package. Though, unpackaged.el is targeting personal use.
