### ISSUE TITLE
org-return-dwim Inserts Heading Instead of Item

### ISSUE THREAD

**Issue by kevinjfoley** [alphapapa/unpackaged.el#2]
I believe the line below should use `org-insert-item` instead of `org-insert-heading`.

https://github.com/alphapapa/unpackaged.el/blob/370cfb943a34cd11b7f2863c28583e8ec1eb1338/unpackaged.el#L510

BTW really useful function, thanks for sharing!

**Comment by alphapapa** [comment]
Hi,

You might think so, but that function actually does both:
```
(org-insert-heading &optional ARG INVISIBLE-OK TOP)

Insert a new heading or an item with the same depth at point.

If point is at the beginning of a heading or a list item, insert
a new heading or a new item above the current one.  When at the
beginning of a regular line of text, turn it into a heading.
```
Does it behave differently on your system?

Thanks for the kind words.  John Kitchin really deserves the credit for this function, I just tweaked it and published it here.

**Comment by alphapapa** [comment]
BTW, you reminded me about a bug that would cause the last item in a list to be erased if it was another element, like a link.  I just pushed a fix for it.

**Comment by alphapapa** [comment]
Thanks for digging that up.  My Org version is outdated, although it was released after that commit, but I guess it didn't include that change.  I pushed a fix that made the change as you suggested.  Thank you for reporting this!
