### ISSUE TITLE
Error on using unpackaged/lorem-ipsum-overlay

### ISSUE THREAD

**Issue by bmp** [alphapapa/unpackaged.el#27]
Thank you for creating the overlay with lorem ipsum. When using the `M-x unpackaged/lorem-ipsum-overlay`, I get the error,

```
unpackaged/lorem-ipsum-overlay
let: Symbol’s function definition is void: -->
```

I was able to fix this by adding/installing `dash.el` explicitly.

**Comment by alphapapa** [comment]
Hello,

As it says at the top of this repo's readme:

> Functions in this file generally use these helper packages:

>    [dash.el](https://github.com/magnars/dash.el) (including dash-functional)
